version: "3.8"
services:
  builder:
    image: ${IMG}
    volumes:
      - ${PRJ_DIR}:/project:ro
      - ${OUT_DIR}:/out
    ports:
      - 8080:8080
    command:
      - /bin/bash
      - /usr/local/bin/build-then-dev.sh